#!/bin/bash

vim /etc/locale.gen
locale-gen

ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime
hwclock --systohc --utc

vim /etc/mkinitcpio.conf
mkinitcpio -P linux

echo pc > /etc/hostname
passwd
