#!/bin/bash
fdisk /dev/sda

cryptsetup -v -y --cipher aes-xts-plain64 --key-size 256 --hash sha256 --iter-time 2000 --use-urandom --verify-passphrase luksFormat /dev/sda3
cryptsetup open /dev/sda4 SYSTEM

pvcreate /dev/mapper/SYSTEM
vgcreate main /dev/mapper/SYSTEM
lvcreate -L 50GB -n root main
lvcreate -l 100%FREE -n home main

mkfs.fat -F 32 -n UEFI /dev/sda1
mkfs.ext4 -L BOOT /dev/sda2
mkfs.ext4 -L ROOT /dev/mapper/main-root
mkfs.ext4 -L HOME /dev/mapper/main-home

mount -L ROOT /mnt
mkdir /mnt/home
mount -L HOME /mnt/home
mkdir /mnt/boot
mount -L BOOT /mnt/boot
mkdir /mnt/boot/efi
mount -L UEFI /mnt/boot/efi
swapon -L SWAP

pacstrap /mnt base base-devel linux linux-firmware dhcpcd grub mkinitcpio efibootmgr git vim sudo lvm2 dosfstools
genfstab -Lp /mnt > /mnt/etc/fstab
arch-chroot /mnt
